# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDropdown():
  def setup_method(self, method):
    self.driver = webdriver.Chrome(executable_path='C:\webdriver\chromedriver.exe')
    self.vars = {}
    self.driver.get("http://the-internet.herokuapp.com/dropdown")
    self.driver.set_window_size(1050, 660)

  def teardown_method(self, method):
    self.driver.quit()
  
  def test_dropdown(self):

    self.driver.find_element(By.ID, "dropdown").click()
    dropdown = self.driver.find_element(By.ID, "dropdown")
    option1 = dropdown.find_element(By.XPATH, "//option[. = 'Option 1']")
    option1.click()

    assert option1.is_selected()

  def test_dropdown2(self):

    self.driver.find_element(By.ID, "dropdown").click()
    dropdown = self.driver.find_element(By.ID, "dropdown")
    option2 = dropdown.find_element(By.XPATH, "//option[. = 'Option 2']")
    option2.click()

    assert option2.is_selected()







    # self.driver.find_element(By.ID, "dropdown").click()
    # dropdown = self.driver.find_element(By.ID, "dropdown")
    # dropdown.find_element(By.XPATH, "//option[. = 'Option 2']").click()
    # self.driver.find_element(By.ID, "dropdown").click()
  
