# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCgallengingDOM():
  def setup_method(self, method):
    self.driver = webdriver.Chrome(executable_path='C:\webdriver\chromedriver.exe')
    self.vars = {}
    self.driver.get("http://the-internet.herokuapp.com/challenging_dom")
    self.driver.set_window_size(1050, 660)

  def teardown_method(self, method):
    self.driver.quit()
  
  def test_cgallengingDOM1(self):

    self.driver.find_element(By.LINK_TEXT, "edit").click()
    self.driver.find_element(By.LINK_TEXT, "delete").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(1) > td:nth-child(4)").click()
    self.driver.find_element(By.ID, "canvas").click()

    field1 = self.driver.find_element(By.XPATH, "//*[@id='content']/div/div/div/div[2]/table/tbody/tr[1]/td[4]")

    #print(field1.text)

    check_field = field1.text
    assert check_field == "Definiebas0"



  def test_cgallengingDOM2(self):

    botton1 = self.driver.find_element_by_xpath("// *[ @ id = 'canvas']")

    color = botton1.value_of_css_property('color')
    #print(color)
    assert color == 'rgba(34, 34, 34, 1)'


  
